language: node_js
notifications:
  email:
    on_success: always
    on_failure: always
node_js:
  - '10'
script:
  - npm run build-docs
after_success:
  - npm run snapshot
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: gh-pages
  on:
    branch: master
